name: Deploy

on:
  workflow_dispatch:
   push:
    branches: ["main"]

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Build
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          checkName: build
          token: ${{ github.token }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
